<?php

namespace Packfire\Config\Driver;

use org\bovigo\vfs\vfsStream;

/**
 * Test class for IniConfig.
 * Generated by PHPUnit on 2012-07-14 at 05:40:58.
 */
class IniTest extends ConfigTestSetter
{
    protected function setUp()
    {
        $this->prepare('Packfire\\Config\\Driver\\Ini');
    }

    public function testRead()
    {
        $data = <<<EOT
[test]
data=5
route=false
EOT;
        
        $root = vfsStream::setup('root');
        $file = vfsStream::newFile('config.ini');
        $root->addChild($file);
        $file->withContent($data);
        
        $reader = new Ini(vfsStream::url('root/config.ini'));
        $reader->read();

        $this->assertEquals(array('test' => array('data' => 5, 'route' => false)), $reader->get());
    }
}
