<?php

namespace Packfire\Config\Driver;

use org\bovigo\vfs\vfsStream;

/**
 * Test class for JsonConfig.
 * Generated by PHPUnit on 2012-10-28 at 06:37:32.
 */
class JsonTest extends ConfigTestSetter
{
    protected function setUp()
    {
        $this->prepare('Packfire\\Config\\Driver\\Json');
    }

    public function testRead()
    {
        $data = <<<EOT
{
    "test": {
        "data": 5,
        "route": false
    }
}
EOT;
        
        $root = vfsStream::setup('root');
        $file = vfsStream::newFile('config.json');
        $root->addChild($file);
        $file->withContent($data);

        $reader = new Json(vfsStream::url('root/config.json'));
        $reader->read();

        $this->assertEquals(array('test' => array('data' => 5, 'route' => false)), $reader->get());
    }
}
